openapi: 3.0.1
info:
  title: House Listing Compiler API
  description: API for compiling and managing house listings.
  version: '1.0.0'
servers:
  - url: https://houselistcompiler-gptapi-d039efb20188.herokuapp.com
paths:
  /process-listing:
    post:
      operationId: processListing
      summary: Processes a house listing URL and returns compiled data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the house listing to be processed.
      responses:
        '200':
          description: Successfully processed listing
          content:
            application/json:
              schema:
                type: object
                properties:
                  compiledData:
                    type: object
                    # Define more properties here if possible
                    description: The compiled data of the house listing.
        '404':
          description: Listing information not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
